// <auto-generated />
using System;
using DAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BE.Models.Etiqueta", b =>
                {
                    b.Property<int>("IdEtiqueta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_etiqueta");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEtiqueta"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("clave");

                    b.Property<string>("Formulario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formulario");

                    b.HasKey("IdEtiqueta");

                    b.ToTable("ETIQUETA", (string)null);
                });

            modelBuilder.Entity("BE.Models.Idioma", b =>
                {
                    b.Property<int>("IdIdioma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_idioma");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdIdioma"));

                    b.Property<bool>("EsDefault")
                        .HasColumnType("bit")
                        .HasColumnName("es_default");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre");

                    b.HasKey("IdIdioma");

                    b.ToTable("IDIOMA", (string)null);
                });

            modelBuilder.Entity("BE.Models.Traduccion", b =>
                {
                    b.Property<int>("IdTraduccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_traduccion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTraduccion"));

                    b.Property<int>("IdEtiqueta")
                        .HasColumnType("int")
                        .HasColumnName("id_etiqueta");

                    b.Property<int>("IdIdioma")
                        .HasColumnType("int")
                        .HasColumnName("id_idioma");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("texto");

                    b.HasKey("IdTraduccion");

                    b.HasIndex("IdEtiqueta");

                    b.HasIndex("IdIdioma");

                    b.ToTable("TRADUCCION", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Consorcio", b =>
                {
                    b.Property<string>("IdConsorcio")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("id_consorcio");

                    b.Property<int>("CantUnidades")
                        .HasColumnType("int")
                        .HasColumnName("cant_unidades");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("direccion");

                    b.Property<int?>("Dvh")
                        .HasColumnType("int")
                        .HasColumnName("dvh");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nombre");

                    b.HasKey("IdConsorcio");

                    b.ToTable("CONSORCIO", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Consorcistum", b =>
                {
                    b.Property<Guid>("IdConsorcista")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_consorcista")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("dni");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("telefono");

                    b.HasKey("IdConsorcista");

                    b.HasIndex(new[] { "IdUsuario" }, "UQ_CONSORCISTA_usuario")
                        .IsUnique();

                    b.ToTable("CONSORCISTA", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Expensa", b =>
                {
                    b.Property<Guid>("IdExpensa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_expensa")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pendiente")
                        .HasColumnName("estado");

                    b.Property<int>("IdUnidad")
                        .HasColumnType("int")
                        .HasColumnName("id_unidad");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("monto");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasColumnName("periodo");

                    b.Property<DateOnly>("Vencimiento")
                        .HasColumnType("date")
                        .HasColumnName("vencimiento");

                    b.HasKey("IdExpensa");

                    b.HasIndex("IdUnidad");

                    b.ToTable("EXPENSA", (string)null);
                });

            modelBuilder.Entity("DAL.Models.GestorConsorcio", b =>
                {
                    b.Property<int>("IdGestorConsorcio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_gestor_consorcio");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGestorConsorcio"));

                    b.Property<DateOnly>("FechaAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("fecha_asignacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("IdConsorcio")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("id_consorcio");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_usuario");

                    b.HasKey("IdGestorConsorcio");

                    b.HasIndex("IdConsorcio");

                    b.HasIndex(new[] { "IdUsuario", "IdConsorcio" }, "UQ_GESTOR_CONSORCIO")
                        .IsUnique();

                    b.ToTable("GESTOR_CONSORCIO", (string)null);
                });

            modelBuilder.Entity("DAL.Models.HistorialUsuario", b =>
                {
                    b.Property<int>("IdHistorial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_historial");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHistorial"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("accion");

                    b.Property<bool>("ActivoSnap")
                        .HasColumnType("bit")
                        .HasColumnName("activo_snap");

                    b.Property<bool>("BloqueadoSnap")
                        .HasColumnType("bit")
                        .HasColumnName("bloqueado_snap");

                    b.Property<string>("EmailGuardado")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email_guardado");

                    b.Property<DateTime>("FechaCambio")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_cambio");

                    b.Property<Guid>("IdUsuarioActor")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_usuario_actor");

                    b.Property<Guid>("IdUsuarioAuditado")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_usuario_auditado");

                    b.Property<string>("PermisosSnap")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("permisos_snap");

                    b.Property<string>("TelefonoGuardado")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("telefono_guardado");

                    b.Property<string>("UsernameSnap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("username_snap");

                    b.HasKey("IdHistorial");

                    b.HasIndex("IdUsuarioActor");

                    b.HasIndex("IdUsuarioAuditado");

                    b.ToTable("HISTORIAL_USUARIO", (string)null);
                });

            modelBuilder.Entity("DAL.Models.LogBitacora", b =>
                {
                    b.Property<int>("IdLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_log");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLog"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("accion");

                    b.Property<string>("Detalle")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("detalle");

                    b.Property<DateTime>("FechaHora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_hora")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("modulo");

                    b.HasKey("IdLog");

                    b.HasIndex("IdUsuario");

                    b.ToTable("LOG_BITACORA", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Pago", b =>
                {
                    b.Property<Guid>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_pago")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<Guid>("IdExpensa")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_expensa");

                    b.Property<string>("MedioPago")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("medio_pago");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("monto");

                    b.Property<string>("NroComprobante")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nro_comprobante");

                    b.HasKey("IdPago");

                    b.HasIndex("IdExpensa");

                    b.ToTable("PAGO", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Permiso", b =>
                {
                    b.Property<int>("IdPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_permiso");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPermiso"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("codigo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nombre");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("tipo");

                    b.HasKey("IdPermiso");

                    b.HasIndex(new[] { "Codigo" }, "UQ_PERMISO_codigo")
                        .IsUnique();

                    b.ToTable("PERMISO", (string)null);
                });

            modelBuilder.Entity("DAL.Models.PermisoPermiso", b =>
                {
                    b.Property<int>("IdHijo")
                        .HasColumnType("int")
                        .HasColumnName("id_hijo");

                    b.Property<int>("IdPadre")
                        .HasColumnType("int")
                        .HasColumnName("id_padre");

                    b.HasIndex("IdHijo");

                    b.HasIndex(new[] { "IdPadre", "IdHijo" }, "UQ_PP")
                        .IsUnique();

                    b.ToTable("PERMISO_PERMISO", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Proveedor", b =>
                {
                    b.Property<Guid>("IdProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_proveedor")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Cuit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("cuit");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Rubro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("rubro");

                    b.HasKey("IdProveedor");

                    b.HasIndex(new[] { "Cuit" }, "UQ_PROVEEDOR_cuit")
                        .IsUnique();

                    b.HasIndex(new[] { "IdUsuario" }, "UQ_PROVEEDOR_usuario")
                        .IsUnique();

                    b.ToTable("PROVEEDOR", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Servicio", b =>
                {
                    b.Property<Guid>("IdServicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_servicio")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pendiente")
                        .HasColumnName("estado");

                    b.Property<string>("Factura")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("factura");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<string>("IdConsorcio")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("id_consorcio");

                    b.Property<Guid>("IdProveedor")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_proveedor");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("monto");

                    b.HasKey("IdServicio");

                    b.HasIndex("IdConsorcio");

                    b.HasIndex("IdProveedor");

                    b.ToTable("SERVICIO", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Unidad", b =>
                {
                    b.Property<int>("IdUnidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_unidad");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUnidad"));

                    b.Property<string>("Depto")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("depto");

                    b.Property<string>("IdConsorcio")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("id_consorcio");

                    b.Property<string>("Piso")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("piso");

                    b.Property<decimal?>("Superficie")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("superficie");

                    b.HasKey("IdUnidad");

                    b.HasIndex("IdConsorcio");

                    b.ToTable("UNIDAD", (string)null);
                });

            modelBuilder.Entity("DAL.Models.UnidadConsorcistum", b =>
                {
                    b.Property<int>("IdUnidadConsorcista")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_unidad_consorcista");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUnidadConsorcista"));

                    b.Property<Guid>("IdConsorcista")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_consorcista");

                    b.Property<int>("IdUnidad")
                        .HasColumnType("int")
                        .HasColumnName("id_unidad");

                    b.Property<string>("TipoVinculo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tipo_vinculo");

                    b.HasKey("IdUnidadConsorcista");

                    b.HasIndex("IdConsorcista");

                    b.HasIndex("IdUnidad");

                    b.ToTable("UNIDAD_CONSORCISTA", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Usuario", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_usuario")
                        .HasDefaultValueSql("(newid())");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<bool>("Bloqueado")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<int?>("IdIdiomaPreferido")
                        .HasColumnType("int")
                        .HasColumnName("id_idioma_preferido");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("telefono");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tipo_usuario");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("username");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdIdiomaPreferido");

                    b.HasIndex(new[] { "Username" }, "UQ_USUARIO_username")
                        .IsUnique();

                    b.ToTable("USUARIO", (string)null);
                });

            modelBuilder.Entity("DAL.Models.UsuarioPermiso", b =>
                {
                    b.Property<int>("IdUsuarioPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario_permiso");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuarioPermiso"));

                    b.Property<int>("IdPermiso")
                        .HasColumnType("int")
                        .HasColumnName("id_permiso");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_usuario");

                    b.HasKey("IdUsuarioPermiso");

                    b.HasIndex("IdPermiso");

                    b.HasIndex("IdUsuario");

                    b.ToTable("USUARIO_PERMISO", (string)null);
                });

            modelBuilder.Entity("DAL.Models.VerificadorVertical", b =>
                {
                    b.Property<string>("NombreTabla")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre_tabla");

                    b.Property<int>("Dvv")
                        .HasColumnType("int")
                        .HasColumnName("dvv");

                    b.HasKey("NombreTabla");

                    b.ToTable("VERIFICADOR_VERTICAL", (string)null);
                });

            modelBuilder.Entity("BE.Models.Traduccion", b =>
                {
                    b.HasOne("BE.Models.Etiqueta", "IdEtiquetaNavigation")
                        .WithMany("Traducciones")
                        .HasForeignKey("IdEtiqueta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BE.Models.Idioma", "IdIdiomaNavigation")
                        .WithMany("Traducciones")
                        .HasForeignKey("IdIdioma")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdEtiquetaNavigation");

                    b.Navigation("IdIdiomaNavigation");
                });

            modelBuilder.Entity("DAL.Models.Consorcistum", b =>
                {
                    b.HasOne("DAL.Models.Usuario", "IdUsuarioNavigation")
                        .WithOne("Consorcistum")
                        .HasForeignKey("DAL.Models.Consorcistum", "IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_CONSORCISTA_USUARIO");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("DAL.Models.Expensa", b =>
                {
                    b.HasOne("DAL.Models.Unidad", "IdUnidadNavigation")
                        .WithMany("Expensas")
                        .HasForeignKey("IdUnidad")
                        .IsRequired()
                        .HasConstraintName("FK_EXPENSA_UNIDAD");

                    b.Navigation("IdUnidadNavigation");
                });

            modelBuilder.Entity("DAL.Models.GestorConsorcio", b =>
                {
                    b.HasOne("DAL.Models.Consorcio", "IdConsorcioNavigation")
                        .WithMany("GestorConsorcios")
                        .HasForeignKey("IdConsorcio")
                        .IsRequired()
                        .HasConstraintName("FK_GC_CONSORCIO");

                    b.HasOne("DAL.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("GestorConsorcios")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_GC_USUARIO");

                    b.Navigation("IdConsorcioNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("DAL.Models.HistorialUsuario", b =>
                {
                    b.HasOne("DAL.Models.Usuario", "UsuarioActorNavigation")
                        .WithMany()
                        .HasForeignKey("IdUsuarioActor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_HISTORIAL_USUARIO_ACTOR");

                    b.HasOne("DAL.Models.Usuario", "UsuarioAuditadoNavigation")
                        .WithMany()
                        .HasForeignKey("IdUsuarioAuditado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_HISTORIAL_USUARIO_AUDITADO");

                    b.Navigation("UsuarioActorNavigation");

                    b.Navigation("UsuarioAuditadoNavigation");
                });

            modelBuilder.Entity("DAL.Models.LogBitacora", b =>
                {
                    b.HasOne("DAL.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("LogBitacoras")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_LOG_USUARIO");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("DAL.Models.Pago", b =>
                {
                    b.HasOne("DAL.Models.Expensa", "IdExpensaNavigation")
                        .WithMany("Pagos")
                        .HasForeignKey("IdExpensa")
                        .IsRequired()
                        .HasConstraintName("FK_PAGO_EXPENSA");

                    b.Navigation("IdExpensaNavigation");
                });

            modelBuilder.Entity("DAL.Models.PermisoPermiso", b =>
                {
                    b.HasOne("DAL.Models.Permiso", "IdHijoNavigation")
                        .WithMany()
                        .HasForeignKey("IdHijo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("PERMISO_PERMISO_PERMISO_FK_1");

                    b.HasOne("DAL.Models.Permiso", "IdPadreNavigation")
                        .WithMany()
                        .HasForeignKey("IdPadre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("PERMISO_PERMISO_PERMISO_FK");

                    b.Navigation("IdHijoNavigation");

                    b.Navigation("IdPadreNavigation");
                });

            modelBuilder.Entity("DAL.Models.Proveedor", b =>
                {
                    b.HasOne("DAL.Models.Usuario", "IdUsuarioNavigation")
                        .WithOne("Proveedor")
                        .HasForeignKey("DAL.Models.Proveedor", "IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_PROVEEDOR_USUARIO");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("DAL.Models.Servicio", b =>
                {
                    b.HasOne("DAL.Models.Consorcio", "IdConsorcioNavigation")
                        .WithMany("Servicios")
                        .HasForeignKey("IdConsorcio")
                        .IsRequired()
                        .HasConstraintName("FK_SERVICIO_CONSORCIO");

                    b.HasOne("DAL.Models.Proveedor", "IdProveedorNavigation")
                        .WithMany("Servicios")
                        .HasForeignKey("IdProveedor")
                        .IsRequired()
                        .HasConstraintName("FK_SERVICIO_PROVEEDOR");

                    b.Navigation("IdConsorcioNavigation");

                    b.Navigation("IdProveedorNavigation");
                });

            modelBuilder.Entity("DAL.Models.Unidad", b =>
                {
                    b.HasOne("DAL.Models.Consorcio", "IdConsorcioNavigation")
                        .WithMany("Unidads")
                        .HasForeignKey("IdConsorcio")
                        .IsRequired()
                        .HasConstraintName("FK_UNIDAD_CONSORCIO");

                    b.Navigation("IdConsorcioNavigation");
                });

            modelBuilder.Entity("DAL.Models.UnidadConsorcistum", b =>
                {
                    b.HasOne("DAL.Models.Consorcistum", "IdConsorcistaNavigation")
                        .WithMany("UnidadConsorcista")
                        .HasForeignKey("IdConsorcista")
                        .IsRequired()
                        .HasConstraintName("FK_UC_CONSORCISTA");

                    b.HasOne("DAL.Models.Unidad", "IdUnidadNavigation")
                        .WithMany("UnidadConsorcista")
                        .HasForeignKey("IdUnidad")
                        .IsRequired()
                        .HasConstraintName("FK_UC_UNIDAD");

                    b.Navigation("IdConsorcistaNavigation");

                    b.Navigation("IdUnidadNavigation");
                });

            modelBuilder.Entity("DAL.Models.Usuario", b =>
                {
                    b.HasOne("BE.Models.Idioma", "IdiomaPreferidoNavigation")
                        .WithMany()
                        .HasForeignKey("IdIdiomaPreferido");

                    b.Navigation("IdiomaPreferidoNavigation");
                });

            modelBuilder.Entity("DAL.Models.UsuarioPermiso", b =>
                {
                    b.HasOne("DAL.Models.Permiso", "IdPermisoNavigation")
                        .WithMany("UsuarioPermisos")
                        .HasForeignKey("IdPermiso")
                        .IsRequired()
                        .HasConstraintName("FK_UP_PERMISO");

                    b.HasOne("DAL.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("UsuarioPermisos")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_UP_USUARIO");

                    b.Navigation("IdPermisoNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("BE.Models.Etiqueta", b =>
                {
                    b.Navigation("Traducciones");
                });

            modelBuilder.Entity("BE.Models.Idioma", b =>
                {
                    b.Navigation("Traducciones");
                });

            modelBuilder.Entity("DAL.Models.Consorcio", b =>
                {
                    b.Navigation("GestorConsorcios");

                    b.Navigation("Servicios");

                    b.Navigation("Unidads");
                });

            modelBuilder.Entity("DAL.Models.Consorcistum", b =>
                {
                    b.Navigation("UnidadConsorcista");
                });

            modelBuilder.Entity("DAL.Models.Expensa", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("DAL.Models.Permiso", b =>
                {
                    b.Navigation("UsuarioPermisos");
                });

            modelBuilder.Entity("DAL.Models.Proveedor", b =>
                {
                    b.Navigation("Servicios");
                });

            modelBuilder.Entity("DAL.Models.Unidad", b =>
                {
                    b.Navigation("Expensas");

                    b.Navigation("UnidadConsorcista");
                });

            modelBuilder.Entity("DAL.Models.Usuario", b =>
                {
                    b.Navigation("Consorcistum");

                    b.Navigation("GestorConsorcios");

                    b.Navigation("LogBitacoras");

                    b.Navigation("Proveedor");

                    b.Navigation("UsuarioPermisos");
                });
#pragma warning restore 612, 618
        }
    }
}
